name: Setup QEMU Container
description: Set up a podman-powered, QEMU-enabled container for use in workflow steps.
author: Sander Vocke
branding:
   color: yellow
   icon: box

inputs:
  container:
    description: >
      URL of the container to use. It will be started using Podman.
    required: true
  arch:
    description: >
      CPU architecture to use. Null means native (don't pass an architecture explicitly)
    default: null
  podman_args:
    description: >
      Additional arguments to podman.
  initial_delay:
    description: >
      Time to wait for pod to be available, e.g., 500ms, 30s, 5m.
    default: 5m

runs:
  using: composite
  steps:
    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get install -y podman qemu-user-static
      shell: bash
    - name: Setup
      shell: bash
      run: |
        sudo -E ./setup.sh
      working-directory: ${{ github.action_path }}
    - name: Set up command
      shell: bash
      run: |
         ARGS=""
         ARCH_ARGS=""
         if [ ! -z "${{ inputs.arch }}" ]; then
           ARCH_ARGS="--arch ${{ inputs.arch }}"
         fi
         ARGS="$ARGS $ARCH_ARGS ${{ inputs.podman_args }}"
         podman pull $ARCH_ARGS ${{ inputs.container }}
         CMD="podman run $ARGS -v $GITHUB_WORKSPACE:$GITHUB_WORKSPACE --cidfile ${{ github.action_path }}/container_cid ${{ inputs.container }} tail -f /dev/null"
         echo "Full podman command: $CMD"
         echo "PODMAN_CMD=$CMD" >> $GITHUB_ENV
    - name: Run container
      uses: JarvusInnovations/background-action@v1
      with:
        run: $PODMAN_CMD
        wait-on: ${{ github.action_path }}/container_cid
        wait-for: ${{ inputs.initial_delay }}
        log-output-resume: true
    - name: Get CID
      shell: bash
      run: |
        CID=$(cat ${{ github.action_path }}/container_cid)
        echo "__RUNNING_CONTAINER=$CID" >> $GITHUB_ENV
        echo "Container CID: $CID"
